theme = catppuccin-mocha
font-family = "JetBrains Mono"
font-size = 16
auto-update-channel = "tip"
# Performance tweaks
window-vsync = false
resize-overlay = "never"
scrollback-limit = 10485760

# UI enhancements
window-padding-x = 4
window-padding-y = 4
window-theme = "auto"
macos-titlebar-style = "hidden"
cursor-style = "block"
cursor-style-blink = true
font-synthetic-style = "no-bold,no-italic"
unfocused-split-opacity = 0.8
focus-follows-mouse = true
mouse-hide-while-typing = true
font-feature = "-calt,-liga,-dlig"
