" You want Vim, not vi. When Vim finds a vimrc, 'nocompatible' is set anyway.
" We set it explicitely to make our position clear!
set nocompatible

" Set Plugin Manager
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'KeitaNakamura/neodark.vim'
Plugin 'SirVer/ultisnips'
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'honza/vim-snippets'
Plugin 'jiangmiao/auto-pairs' 
Plugin 'majutsushi/tagbar'
Plugin 'mattn/emmet-vim'
Plugin 'mxw/vim-jsx'
Plugin 'pangloss/vim-javascript'
Plugin 'prettier/vim-prettier'
Plugin 'ryanoasis/vim-devicons'
Plugin 'scrooloose/nerdtree'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'valloric/youcompleteme'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-scripts/BufOnly.vim'
Plugin 'wakatime/vim-wakatime'
Plugin 'zefei/vim-colortuner'
call vundle#end()             " required
filetype plugin indent on     " Load plugins according to detected filetype.

" clipboard
set clipboard^=unnamed,unnamedplus

" Nerd Tree
map <C-n> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
if argc() == 0 && !exists("s:std_in")
  autocmd vimenter * NERDTree
else
  autocmd vimenter * NERDTree
  autocmd vimenter * wincmd l
endif

" Themes
if !exists("g:syntax_on")
  syntax enable
endif
if (has("termguicolors"))
  set termguicolors
endif
if has('gui_running')
  set background=light
else
  set background=dark
endif
colorscheme neodark
let g:neodark#use_256color = 1
let g:neodark#use_custom_terminal_theme = 1
set fdm=syntax
nnoremap zo za
nnoremap zO zA

" Vim Airline
let g:lightline = {}
let g:lightline.colorscheme = 'neodark'
let g:airline#extensions#tabline#enabled = 1  
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_match_window = 'top,order:btt,min:1,max:20,results:20'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/*,*/dist/*

" vim-devicon
let g:airline_powerline_fonts = 1

" Javascript Plugin Settings
let g:javascript_plugin_flow = 1
let g:jsx_ext_required = 1

" Prettier Settings
let g:prettier#config#trailing_comma = 'none'

" ctrlp funky
nnoremap <Leader>fu :CtrlPFunky<Cr>
nnoremap <Leader>fU :execute 'CtrlPFunky ' . expand('<cword>')<Cr>
let g:ctrlp_funky_matchtype = 'path'
let g:ctrlp_funky_syntax_highlight = 1

" UtilSnips
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

" tags bar
nmap <F8> :TagbarToggle<CR>

" Line Number Setting
set number relativenumber
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

" neo vim
if !has('nvim')
  set ttymouse=xterm2
endif

" Split Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-O> <C-W><C-O>

" Control + s for vim
inoremap <C-S> <esc>:w<cr>i

" remap jk to <esc>
inoremap jj <esc>

" disable arrow key
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <up> <nop>

" Abbrev
iabbrev amk Aung Myo Kyaw

set autoread " Auto refresh buffer
set hidden " Leave hidden buffers open
set ic " ignore case for search

set autoindent             " Indent according to previous line.
set expandtab              " Use spaces instead of tabs.
set softtabstop =2         " Tab key indents by 4 spaces.
set shiftwidth  =2         " >> indents by 4 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

set backspace   =indent,eol,start  " Make backspace work as you would expect.
set hidden                 " Switch between buffers without having to save first.
set laststatus  =2         " Always show statusline.
set display     =lastline  " Show as much as possible of the last line.

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set incsearch              " Highlight while searching with / or ?.
set hlsearch               " Keep matches highlighted.

set ttyfast                " Faster redrawing.
set lazyredraw             " Only redraw when necessary.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

set cursorline             " Find the current line quickly.
set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.
set synmaxcol   =200       " Only highlight the first 200 columns.
set encoding    =utf8
