version: 1

agent:
  # Additional system prompt to append to the agent's default system prompt
  additionalSystemPrompt: null
  # Enable streaming responses from the AI model
  streaming: true
  # Temperature setting for AI model responses (0.0-1.0)
  temperature: 0.3
  experimental:
    # Enable/disable the agent to run in shadow mode. This will run the agent on
    # a temporary clone of your workspace, prompting you before any changes are
    # applied to your working directory.
    enableShadowMode: false

sessions:
  # Automatically restore the last active session on startup
  autoRestore: false
  # Directory where session data is stored
  persistenceDir: /Users/aungmyokyaw/.rovodev/sessions

console:
  # Output format for console display (markdown, simple, or raw)
  outputFormat: markdown
  # Show tool execution results in the console
  showToolResults: true
  # Maximum width of the console output in characters, or 'fill' to fill the
  # terminal width
  maxOutputWidth: 120

logging:
  # Path to the log file
  path: /Users/aungmyokyaw/.rovodev/rovodev.log

mcp:
  # Path to the MCP (Model Context Protocol) configuration file
  mcpConfigPath:
    /Users/aungmyokyaw/Library/CloudStorage/GoogleDrive-realaungmyokyaw@gmail.com/My
    Drive/Dropbox/private/dotfiles-via-stow/rovodev/mcp.json

toolPermissions:
  # Default permission for tools not explicitly listed
  default: allow
  # Permission settings for specific tools
  tools:
    create_file: allow
    delete_file: allow
    find_and_replace_code: allow
    open_files: allow
    expand_code_chunks: allow
    expand_folder: allow
    grep_file_content: allow
    grep_file_paths: allow
    getAccessibleAtlassianResources: allow
    getConfluenceSpaces: allow
    getConfluencePages: allow
    getPagesInConfluenceSpace: allow
    getConfluencePageAncestors: allow
    getConfluencePageFooterComments: allow
    getConfluencePageInlineComments: allow
    getConfluencePageDescendants: allow
    searchConfluenceUsingCql: allow
    getJiraIssue: allow
    getTransitionsForJiraIssue: allow
    lookupJiraAccountId: allow
    searchJiraIssuesUsingJql: allow
    getJiraIssueRemoteIssueLinks: allow
    getVisibleJiraProjects: allow
    getJiraProjectIssueTypesMetadata: allow
    createConfluencePage: ask
    updateConfluencePage: ask
    createConfluenceFooterComment: ask
    createConfluenceInlineComment: ask
    editJiraIssue: ask
    createJiraIssue: ask
    transitionJiraIssue: ask
    addCommentToJiraIssue: ask
    create_technical_plan: allow
  bash:
    # Default permission for bash commands not explicitly listed
    default: allow
    # List of specific bash commands with their permission settings
    commands:
      - command: ls.*
        permission: allow
      - command: cat.*
        permission: allow
      - command: echo.*
        permission: allow
      - command: git status
        permission: allow
      - command: git diff.*
        permission: allow
      - command: git log.*
        permission: allow
      - command: pwd
        permission: allow
  # List of allowed MCP server names
  allowedMcpServers:
    - npx -y @modelcontextprotocol/server-sequential-thinking
    - npx -y @upstash/context7-mcp
    - uvx mcp-server-fetch
    - npx -y @modelcontextprotocol/server-puppeteer
    - npx -y @modelcontextprotocol/server-memory
  # List of file or directory paths that are allowed to be accessed outside the
  # workspace
  allowedExternalPaths:
    - ~/workspace
    - /tmp
