#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme                    = "hybrid"
    background                     = "dark"
    enable_guicolors               = true
    statusline_separator           = "arrow"
    statusline_inactive_separator  = "arrow"
    buffer_index_type              = 4
    enable_tabline_filetype_icon   = true
    enable_statusline_display_mode = false
    bootstrap_before               = "myspacevim#before"
    bootstrap_after                = "myspacevim#after"

# colorschemes
[[layers]]
name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name                                = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior    = "smart"

[[layers]]
name             = "shell"
default_position = "bottom"
default_height   = 30

# Better default config for vim and neovim.
[[layers]]
name = "default"

# VersionControl
[[layers]]
name = "VersionControl"

# ctrlp
[[layers]]
name = "ctrlp"

# JAVASCRIPT
[[layers]]
name               = "lang#javascript"
auto_fix           = true
enable_flow_syntax = true

# TYPESCRIPT
[[layers]]
name = "lang#typescript"

# EJS
[[custom_plugins]]
name = "briancollins/vim-jst"
merged = 0

# EXTRA/LANG
[[layers]]
name = "lang#extra"
merged = 0

#=================
# CUSTOM PLUGINS
#=================

[[custom_plugins]]
name = "prettier/vim-prettier"
merged = 0

[[custom_plugins]]
name = "vimwiki/vimwiki"
merged = 0

[[custom_plugins]]
name = "wakatime/vim-wakatime"
merged = 0
