# TMUX prefix
set-option -g prefix C-a

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Save Interval
set -g @continuum-save-interval '5'

# Auto Restore
# set -g @continuum-restore 'on'

# Enable TRUE COLOR
# run echo $TERM outside of tmux
# replace XXX with $TERM vlaue
# set-option -sa terminal-overrides ',XXX:RGB'
set-option -sa terminal-overrides ',xterm-256color:RGB'

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# use vi style keybinding
setw -g mode-keys vi

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
