# PATH TO YOUR OH-MY-ZSH INSTALLATION.
export ZSH=~/.oh-my-zsh

# SIGN COMMIT
export GPG_TTY=$(tty)

# THEMES
ZSH_THEME="robbyrussell"

# PLUGINS
plugins=(git)

source $ZSH/oh-my-zsh.sh

# ALIAS

# UTF 8/256 COLOR SUPPORT TMUX
alias tmux='tmux -u -2'

# DNVIM
alias dnvim='docker run -it --rm \
  -v $(pwd):/home/spacevim/src \
  -v ~/dockerized-nvim/.local/share/nvim/:/home/spacevim/.local/share/nvim:cached \
  -v ~/dockerized-nvim/.cache:/home/spacevim/.cache:cached \
  dnvim'

# COPYTO SYSTEM CLIPBOARD
alias dcp='cat ./dcp.txt | pbcopy'

# USER ALIASES
source ~/.aliases
