# PATH TO YOUR OH-MY-ZSH INSTALLATION.
export ZSH=~/.oh-my-zsh

# SIGN COMMIT
export GPG_TTY=$(tty)

# FZF
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git/*"'

# THEMES
ZSH_THEME="robbyrussell"
# ZSH_THEME="spaceship"
# SPACESHIP_PROMPT_ADD_NEWLINE=false

# PLUGINS
plugins=(
  git
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh

# ALIAS

# UTF 8/256 COLOR SUPPORT TMUX
alias tmux='tmux -u -2'

# USER ALIASES
source ~/.aliases

# ZSH TMUX SETTINGS
# ZSH_TMUX_AUTOSTART='true'
